version: '3.9'

services:

  flask-app:
  image: 455025093404.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app:latest
  container_name: flask-app
  restart: unless-stopped
  networks:
    - monitoring
  # no ports exposed externally

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: "host"
    pid: host                  # ← add this, needed to read host metrics
    volumes:                   # ← add this block, needed for host metrics
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    # removed ports: — conflicts with network_mode: host


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"   # Prometheus dashboard in browser
    networks : 
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"   # Grafana dashboard in browser
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=SuhaniSharma
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-clock-
    networks: 
      - monitoring

networks:
  monitoring:
    driver: bridge