name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::455025093404:role/github-actions-ecr-role
          aws-region: us-east-1
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 455025093404.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app
      - name: Build Docker Image
        run: |
          docker build -t cicd-app -f ./app/Dockerfile ./app
      
      - name: Tag Docker Image
        run: |
          docker tag cicd-app:latest 455025093404.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app:latest
      - name: Push Docker Image
        run: |
          docker push 455025093404.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app:latest
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh 
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@3.215.249.25 << 'EOF'
            
            # login to ECR
            aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin 455025093404.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app
            
            # Stop old container if it exists
            docker stop cicd-app || true
            docker rm -f cicd-app || true
            docker container prune -f

            # Pull latest image from ECR
            docker pull 455025093404.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app:latest
     
            # Run the container
            docker run -d  -p 80:5000 --name cicd-app 455025093404.dkr.ecr.us-east-1.amazonaws.com/cicd-python-app:latest
          EOF
        shell: bash